### ISSUE TITLE
instructions  for install and running.

### ISSUE THREAD

**Issue by sbeckeriv** [pest-parser/pest-fmt#2]
Dearest Maintainer,

In the readme it would be nice to know how it is expected to be installed and ran.  I tried via cargo install first but it says there is nothing.  If nothing else it would prevent a new person from fumbling around.

Thank you for your consideration,

Dictated but not reviewed,
Becker

**Comment by ice1000** [comment]
This is supposed to be a function invoked by some program, ideally intellij-pest. However, the development is paused due to lack of time and energy of the developers.

**Comment by sbeckeriv** [comment]
thanks @ice1000 for the reply. i am closing this.

**Comment by GalAster** [comment]
Todo: add the cli

**Comment by xiaket** [comment]
@oovm Do we have an update on this? If not, do you mind if I use clap to parse the command line arguments and send them to `Settings.format_file`?

**Comment by oovm** [comment]
Contact `https://github.com/pest-parser` if you want to take ownership of the repo.

If you want to release a new version on crates.io, please let me know your crate id.

**Comment by ice1000** [comment]
> Contact `https://github.com/pest-parser` if you want to take ownership of the repo.
> 
> If you want to release a new version on crates.io, please let me know your crate id.

I think you can merge PR anyway
