### ISSUE TITLE
Option for stdin/stdout operation

### ISSUE THREAD

**Issue by Davey-Hughes** [pest-parser/pest-fmt#26]
Is it possible to add an option to format by reading from stdin and then printing to stdout? It would make it easier for me to integrate with neovim if this option is available.

I can give the implementation a go and make a PR if this is desired.

**Comment by tomtau** [comment]
@huacnlee I think that should be all right, what do you think?
@Davey-Hughes note that Neovim has support for formatting via https://github.com/pest-parser/pest-ide-tools by @Jamalam360

**Comment by huacnlee** [comment]
I will going to add this option.

**Comment by Davey-Hughes** [comment]
Ah I'm so silly. I didn't have my lsp formatting settings correct. Thank you so much for adding the --stdin option anyway.
